# -*- coding: utf-8 -*-
"""oss개발 5/2일

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TUTxh7ml18BxBzOlOcXPaumpUxB2QGj
"""

!pip install geopandas

import geopandas as gpd

path_to_data = gpd.datasets.get_path("nybb")
gdf = gpd.read_file(path_to_data)

gdf

gdf.to_file("my_file.geojson", driver = "GeoJSON")

gdf = gdf.set_index("BoroName")

gdf["area"] = gdf.area
gdf["area"]

gdf['boundary'] = gdf.boundary
gdf['boundary']

gdf['centroid'] = gdf.centroid
gdf['centroid']

first_point = gdf['centroid'].iloc[0]
gdf['distance'] = gdf['centroid'].distance(first_point)
gdf['distance']

gdf['distance'].mean()

gdf.plot("area", legend=True)

ax = gdf["geometry"].plot()
gdf["centroid"].plot(ax=ax, color="black")